<?php

class controller_404 extends Controller {

    public function action()
    {
        parent::action(); // TODO: Change the autogenerated stub
        $this->view->render('404_view.php', 'template_view.php');
    }
}






//$control = new Controller();
//$content_view = '404_view.php';
//$name = 'template_view.php';
//$control->render($content_view, $name);