<?php

class main extends Controller {

    public function action()
    {
//        parent::action(); // TODO: Change the autogenerated stub
//        $this->view->render('main_view.php', 'template_view.php');

        $this->view->generate("main_view.twig");
    }
}

//$control = new Controller();
//$content_view = 'main_view.php';
//$name = 'template_view.php';
//$control->render($content_view, $name);
